version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx-container
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend-container
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    build:
      context: ./database
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/mysqlData:/var/lib/mysql

