FROM nginx:latest

EXPOSE 80 443

#WORKDIR /etc/nginx/
#COPY conf.d/* conf.d/ #use if docker volume not mounted
####################################################################
# FROM nginx:latest
## Set the working directory as /etc/nginx
#WORKDIR /etc/nginx/
#
## Copy the custom nginx configuration file into the container
#COPY application.conf conf.d/default.conf
## COPY ssl ssl_certificate  ## if you have ssl certificates
#
## Expose ports
#EXPOSE 80 443
